### ISSUE TITLE
`create_element!` does not support attributes with dimension

### ISSUE THREAD

**Issue by pedroripper** [psrenergy/PSRClassesInterface.jl#126]
We define if an attribute has dimension > 0 in the PMD file

```
DEFINE_MODEL MODL:SDDP_ElectrificationDemandSegment
        DIMENSION	block
	VETOR DATE 	Data
	VETOR REAL 	Demanda	DIM(block) INDEX Data  🔴 
	VETOR DATE 	DataCusto
	VETOR REAL 	Custo	DIM(block) INDEX DataCusto   🔴 

	//--------------------------------------
	//--- Demanda Horaria                ---
	//--------------------------------------
	VETOR DATE 	DataHourDemand
	VETOR REAL 	HourDemand INDEX DataHourDemand
	VETOR DATE 	DataHourDemandPrice
	VETOR REAL 	HourDemandPrice INDEX DataHourDemandPrice
END_MODEL
```

And currently, when we parse a PMD file, we create a `Vector{Dict{String , Attribute}}` for `data.data_struct`. An `Attribute` has the following structure: 

```julia
Attribute(
       "Attribute name", 
       is_a_vector,  # bool
       Type,
       Dimension,    # 0<= dimension
       "Attribute that works as index to the vector"  # can be ""
)
```

So for the attributes `Demanda` and `Custo` from `PSRDemandSegment`, the dimension parameter is 1.

```julia
Dict{String, PSRClassesInterface.PMD.Attribute}(
      ... ,
      "Demanda" => PSRClassesInterface.PMD.Attribute("Demanda", true, Float64, 1, "Data"), 
      "Custo" => PSRClassesInterface.PMD.Attribute("Custo", true, Float64, 1, "DataCusto"), 
      ...
)

```

However, when we try to create an element from `PSRDemandSegment` (or any other that has attributes with dimension > 0), we cannot define the attribute value for each block/segment/stage.

```julia
julia> PSRI.create_element!(data, "PSRDemandSegment", "Demanda(1)" => [1.0,1.2,1.3])
ERROR: Invalid attributes for collection 'PSRDemandSegment':
    Demanda(1)

```

That happens because when creating an element, we check if the attribute name is a key for the `data.data_struct[collection]` dictionary, and there's no `Demanda(1)` key, only `Demanda`. 

```julia
function _validate_element(data::Data, collection::String, element::Dict{String,Any})
    data_struct = get_data_struct(data)

    collection_struct = data_struct[collection]
    collection_keys = Set{String}(keys(collection_struct))

    element_keys = Set{String}(keys(element))
    missing_keys = setdiff(collection_keys, element_keys)
    invalid_keys = setdiff(element_keys, collection_keys)

   ... 

    if !isempty(invalid_keys)
        error("""
              Invalid attributes for collection '$collection':
                  $(join(invalid_keys, "\n    "))
              """)
    end

   ...
    return nothing
end

```

**Comment by pedroripper** [comment]
I suggest that for the invalid keys, we first remove their parenthesis (if they have) and then re-check if they are a key for the `data.data_struct[collection]`. If that's true, we then confirm if the dimension is correct according to the attribute definition.

**Comment by pedroripper** [comment]
Another issue is that for every attribute that was not defined when creating an element, we fill it with its default value stated in a JSON.

And for attributes that have dimension > 0 , we are filling them as if they had dimension 0. See the default value for `Demanda` in `PSRDemandSegment`:

```json
"PSRDemandSegment": {
        "DataHourDemand": [
            "1900-01-01"
        ],
        "Demanda": [
            0.0
        ],
       ...
}



```

**Comment by pedroripper** [comment]
This is how the JSON defaults should be:

```json
 "Demanda(1)": [
      0.38948,
      0.35179,
      0.38948
  ],
  "Demanda(2)": [
      0.64914,
      0.58632,
      0.64914
  ],
  "Demanda(3)": [
      1.5579,
      1.4072,
      1.5579
  ]
```

**Comment by guilhermebodin** [comment]
In my opinion, we should have a custom function for those cases that constructs the correct string under the hood. It should be noted in this case that if the attribute has a dimension different than 0 this should be the only way to create the element.
