### ISSUE TITLE
Erro na obtenção de parâmetros de térmicas via função mapped_vector

### ISSUE THREAD

**Issue by jmdvilela** [psrenergy/PSRClassesInterface.jl#14]
**Caso**
http://psr.me/66izm4

**Problema**
status   = PSRI.mapped_vector(data, "PSRThermalPlant", "Existing", Int32)
![image](https://user-images.githubusercontent.com/42416240/133841981-4ef3d5c0-160a-4d90-9ab1-891f72667850.png)

capacity = PSRI.mapped_vector(data, "PSRThermalPlant", "PotInst", Float64)
![image](https://user-images.githubusercontent.com/42416240/133842138-b6d83b42-fec2-4ad7-b813-c2d05aad2483.png)

rodando _em seguida_ mais uma vez aparece esse outro erro
capacity = PSRI.mapped_vector(data, "PSRThermalPlant", "PotInst", Float64)
![image](https://user-images.githubusercontent.com/42416240/133842227-d2dab59b-a754-4c87-8ccc-46f1cf04bf20.png)

**Comment by jmdvilela** [comment]
Acho que deve estar relacionado com esse erro que obtive em seguida.

**Problema**

PSRI.go_to_stage(data, 1)
PSRI.go_to_dimension(data, "segment", 1)
![image](https://user-images.githubusercontent.com/42416240/133844230-f2fd8465-8e0d-4a94-8815-59d9d07c7bc7.png)

PSRI.go_to_dimension(data, "block", 1)
![image](https://user-images.githubusercontent.com/42416240/133844266-1bba3d69-ac6c-497b-b8db-3fad6c71919e.png)

**Comment by joaquimg** [comment]
This works on my end:
```julia
PATH_CASE_1 = joinpath(".", "data", "caso1")

data = PSRI.initialize_study(
    PSRI.OpenInterface(),
    data_path = PATH_CASE_0
)

@show status = PSRI.mapped_vector(data, "PSRThermalPlant", "Existing", Int32)

@show capacity = PSRI.mapped_vector(data, "PSRThermalPlant", "PotInst", Float64)

```
