### ISSUE TITLE
Unable to get some parameters from PSRBattery 

### ISSUE THREAD

**Issue by jmdvilela** [psrenergy/PSRClassesInterface.jl#31]
# --- import database from json
data = PSRI.initialize_study(
        PSRClassesInterface.OpenInterface(),
        data_path = casepath
);

# --- get battery parameters
PSRI.mapped_vector(data, "PSRBattery", "Einic", Float64)
PSRI.mapped_vector(data, "PSRBattery", "ChargeRamp", Float64)
PSRI.mapped_vector(data, "PSRBattery", "DischargeRamp" , Float64)

![image](https://user-images.githubusercontent.com/42416240/135461607-2180fe4a-905a-4fa8-b665-66f903842438.png)

**Comment by joaquimg** [comment]
These are not vectors, they are parms, use:
```julia
PSRI.get_parms(data, "PSRBattery", "Einic", Float64)
PSRI.get_parms(data, "PSRBattery", "ChargeRamp", Float64)
PSRI.get_parms(data, "PSRBattery", "DischargeRamp", Float64)
```
