### ISSUE TITLE
Unable to access circuit attribute "FlagMonitored"

### ISSUE THREAD

**Issue by jmdvilela** [psrenergy/PSRClassesInterface.jl#53]
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)       
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64    
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA = C:\Users\jvilela\AppData\Local\Programs\Julia-1.6.2\bin\julia.exe
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =

     Project Tariff2 v0.1.0
      Status `D:\Development\Tariff2\compile\Tariff2\Project.toml`
  [1eab49e5] PSRClassesInterface v0.3.1 `git@github.com:psrenergy/PSRClassesInterface.jl.git#master`

Trying to run:
PSRI.get_parms(data, "PSRSerie", "FlagMonitored", Int32)

But i'm getting this error:
![image](https://user-images.githubusercontent.com/42416240/143291198-85c9eb47-c126-4f63-8513-ef900efd75b3.png)

From the .pmk's looks like this attribute is a parameter, so it should work.
Cmon		INTEGER		119,119	AUTOSET(model.parm("FlagMonitored"))

**Comment by guilhermebodin** [comment]
Fixed in the .dat implementation
